<#
.SYNOPSIS
  Builds FRENCH_REVIEW.md from the shipped Keyed and DefInjected XML, for TRANSLATIONS.md's
  "Systematic French review by Virginie" (2026-09-30).
.DESCRIPTION
  Adapted from FoodCourt's _tools/Generate-FrenchReview.ps1. Reads every
  Mod/Languages/French/{Keyed,DefInjected}/**/*.xml key. For each key, resolves the English text:
  a matching Mod/Languages/English file+key if one exists, otherwise the native English value read
  directly from the shipped Def in Mod/Defs (label/description/stage/tool fields resolved by
  dotted path against the Def's own XML).

  Original (source-language) text: this mod's Defs were ported straight to English (the native
  field holds "qiongqi", "bite", not Chinese — checked 2026-09-30, Mod/Defs/Pawn/QiongQi.xml), and
  no separate Chinese-language field exists anywhere in this repository (ATTRIBUTION.md: a licence
  review found no source repository, so no upstream Chinese file to read from either). Original
  therefore equals English throughout, same as the FoodCourt script's own Miruku/Dandelions case.
#>
param(
    [string]$Root = (Split-Path $PSScriptRoot -Parent),
    [string]$OutFile = (Join-Path (Split-Path $PSScriptRoot -Parent) 'FRENCH_REVIEW.md')
)

function Get-Entries($path) {
    $entries = [ordered]@{}
    if (-not (Test-Path $path)) { return $entries }
    $xml = [xml](Get-Content $path -Raw -Encoding UTF8)
    foreach ($node in $xml.LanguageData.ChildNodes) {
        if ($node.NodeType -ne 'Element') { continue }
        $entries[$node.Name] = $node.InnerText
    }
    return $entries
}

function Resolve-DefField($defsRoot, [string]$key) {
    # key looks like "DefName.field" or "DefName.stages.N.field" or "DefName.tools.N.label"
    $parts = $key -split '\.'
    $defName = $parts[0]
    $rest = $parts[1..($parts.Length - 1)]
    if (-not $script:defCache.ContainsKey($defName)) {
        $found = $null
        foreach ($f in $script:defFiles) {
            $x = [xml](Get-Content $f -Raw -Encoding UTF8)
            $node = $x.SelectSingleNode("//*[defName='$defName']")
            if ($node) { $found = $node; break }
        }
        $script:defCache[$defName] = $found
    }
    $node = $script:defCache[$defName]
    if (-not $node) { return $null }
    $cur = $node
    foreach ($p in $rest) {
        if ($cur -eq $null) { return $null }
        if ($p -match '^\d+$') {
            $children = @($cur.ChildNodes | Where-Object { $_.NodeType -eq 'Element' })
            $idx = [int]$p
            if ($idx -ge $children.Count) { return $null }
            $cur = $children[$idx]
        } else {
            $cur = $cur.$p
        }
    }
    if ($cur -is [System.Xml.XmlElement]) { return $cur.InnerText }
    if ($cur) { return [string]$cur }
    return $null
}

$frenchRoot = Join-Path $Root 'Mod/Languages/French'
$englishRoot = Join-Path $Root 'Mod/Languages/English'
$defsRoot = Join-Path $Root 'Mod/Defs'
$script:defFiles = Get-ChildItem $defsRoot -Recurse -Filter *.xml | ForEach-Object { $_.FullName }
$script:defCache = @{}

$frenchFiles = Get-ChildItem $frenchRoot -Recurse -Filter *.xml | Sort-Object FullName
$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("# French review")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated by ``Tests/Generate-FrenchReview.ps1`` for TRANSLATIONS.md's systematic French review.")
[void]$out.AppendLine("**Original column: same as English throughout.** This mod's Defs were ported straight to")
[void]$out.AppendLine("English (the native field holds English, not Chinese) and no separate Chinese-language file")
[void]$out.AppendLine("exists in this repository (ATTRIBUTION.md: no source repository was found to read one from).")
[void]$out.AppendLine("English is the closest available original for every row.")
[void]$out.AppendLine()
$rev = (git -C $Root rev-parse --short HEAD 2>$null)
[void]$out.AppendLine("Generated $(Get-Date -Format 'yyyy-MM-dd'), revision: $rev.")
[void]$out.AppendLine()

foreach ($ff in $frenchFiles) {
    $rel = $ff.FullName.Substring($frenchRoot.Length + 1) -replace '\\', '/'
    $frEntries = Get-Entries $ff.FullName
    if ($frEntries.Count -eq 0) { continue }

    $enPath = Join-Path $englishRoot $rel
    $enEntries = Get-Entries $enPath

    [void]$out.AppendLine("## $rel")
    [void]$out.AppendLine()
    [void]$out.AppendLine("| Key or path | Original | English | French |")
    [void]$out.AppendLine("|---|---|---|---|")
    foreach ($key in $frEntries.Keys) {
        $fr = $frEntries[$key]
        $en = $null
        if ($enEntries.Contains($key)) { $en = $enEntries[$key] }
        else { $en = Resolve-DefField $defsRoot $key }
        if ($null -eq $en) { $en = '*(not found — check by hand)*' }
        $orig = $en
        $flag = if ($fr -match '\?\?\?|TODO|\{PAWN_gender' -and $fr -notmatch '\{PAWN_gender \? ') { ' | ?' } else { '' }
        $origCell = ($orig -replace '\|', '\|') -replace "`n", ' '
        $enCell = ($en -replace '\|', '\|') -replace "`n", ' '
        $frCell = ($fr -replace '\|', '\|') -replace "`n", ' '
        $keyCell = $key -replace '\|', '\|'
        [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell$flag |")
    }
    [void]$out.AppendLine()
}

[System.IO.File]::WriteAllText($OutFile, $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "wrote $OutFile"
