<#
.SYNOPSIS
  Builds FRENCH_REVIEW.md from the shipped Keyed and DefInjected XML, for TRANSLATIONS.md's
  "Systematic French review by Virginie" (2026-09-30).
.DESCRIPTION
  Adapted from FoodCourt's _tools/Generate-FrenchReview.ps1. Reads every
  Mod/Languages/French/{Keyed,DefInjected}/**/*.xml key. For each key, resolves the English text:
  a matching Mod/Languages/English file+key if one exists, otherwise the native English value read
  directly from the shipped Def in Mod/Defs (label/description/stage/tool fields resolved by
  dotted path against the Def's own XML).

  Original (source-language) text: this mod's Defs were ported straight to English (the native
  field holds "qiongqi", "bite", not Chinese — checked 2026-09-30, Mod/Defs/Pawn/QiongQi.xml), and
  no separate Chinese-language field exists anywhere in this repository (ATTRIBUTION.md: a licence
  review found no source repository, so no upstream Chinese file to read from either). Original
  therefore equals English throughout, same as the FoodCourt script's own Miruku/Dandelions case.
#>
param(
    [string]$Root = (Split-Path $PSScriptRoot -Parent),
    [string]$OutFile = (Join-Path (Split-Path $PSScriptRoot -Parent) 'FRENCH_REVIEW.md')
)

function Get-Entries($path) {
    $entries = [ordered]@{}
    if (-not (Test-Path $path)) { return $entries }
    $xml = [xml](Get-Content $path -Raw -Encoding UTF8)
    foreach ($node in $xml.LanguageData.ChildNodes) {
        if ($node.NodeType -ne 'Element') { continue }
        $entries[$node.Name] = $node.InnerText
    }
    return $entries
}

function Get-DefNode([string]$defName) {
    if (-not $script:defCache.ContainsKey($defName)) {
        # several defs of different types can share a defName (a SoundDef and a ThingDef): keep them all
        $found = @()
        foreach ($f in $script:defFiles) {
            $x = [xml](Get-Content $f -Raw -Encoding UTF8)
            $found += @($x.SelectNodes("//*[defName='$defName']"))
        }
        $script:defCache[$defName] = $found
    }
    return $script:defCache[$defName]
}

function Get-ParentNode($node) {
    $pn = $node.GetAttribute('ParentName')
    if (-not $pn) { return $null }
    if (-not $script:nameCache.ContainsKey($pn)) {
        $found = $null
        foreach ($f in $script:defFiles) {
            $x = [xml](Get-Content $f -Raw -Encoding UTF8)
            $n = $x.SelectSingleNode("//*[@Name='$pn']")
            if ($n) { $found = $n; break }
        }
        $script:nameCache[$pn] = $found
    }
    return $script:nameCache[$pn]
}

# One step down a dotted path: a child element name, a list index, or a label handle (the translation
# system names a list item by its label, spaces turned into underscores).
function Step-Path($cur, [string]$p) {
    $children = @($cur.ChildNodes | Where-Object { $_.NodeType -eq 'Element' })
    if ($p -match '^\d+$') {
        $idx = [int]$p
        if ($idx -ge $children.Count) { return $null }
        return $children[$idx]
    }
    $direct = $children | Where-Object { $_.Name -eq $p } | Select-Object -First 1
    if ($direct) { return $direct }
    foreach ($li in $children) {
        foreach ($f in 'label','untranslatedCustomLabel','customLabel','def','defName') {
            $v = $li.SelectSingleNode($f)
            if ($v -and (($v.InnerText.Trim() -replace '\s+','_') -ieq $p)) { return $li }
        }
        $cls = $li.GetAttribute('Class')
        # HediffCompProperties_VerbGiver is addressed as HediffComp_VerbGiver
        if ($cls -and ((($cls -split '\.')[-1] -replace 'Properties','') -ieq ($p -replace 'Properties',''))) { return $li }
    }
    return $null
}

function Resolve-From($node, [string[]]$rest) {
    $cur = $node
    foreach ($p in $rest) {
        if ($null -eq $cur) { return $null }
        $cur = Step-Path $cur $p
    }
    if ($cur -is [System.Xml.XmlElement]) { return $cur.InnerText }
    return $null
}

function Resolve-DefField($defsRoot, [string]$key) {
    # "DefName.field", "DefName.stages.N.field", "DefName.tools.fang.label" (a field the def does not
    # set comes from its abstract parent)
    $parts = $key -split '\.'
    $rest = $parts[1..($parts.Length - 1)]
    foreach ($start in @(Get-DefNode $parts[0])) {
        $node = $start
        while ($node) {
            $r = Resolve-From $node $rest
            if ($r) { return $r }
            $node = Get-ParentNode $node
        }
    }
    return $null
}

$frenchRoot = Join-Path $Root 'Mod/Languages/French'
$englishRoot = Join-Path $Root 'Mod/Languages/English'
$defsRoot = Join-Path $Root 'Mod/Defs'
$script:defFiles = Get-ChildItem $defsRoot -Recurse -Filter *.xml | ForEach-Object { $_.FullName }
$script:defCache = @{}
$script:nameCache = @{}

$frenchFiles = Get-ChildItem $frenchRoot -Recurse -Filter *.xml | Sort-Object FullName
$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("# French review")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated by ``Tests/Generate-FrenchReview.ps1`` for TRANSLATIONS.md's systematic French review.")
[void]$out.AppendLine("**Original column: same as English throughout.** This mod's Defs were ported straight to")
[void]$out.AppendLine("English (the native field holds English, not Chinese) and no separate Chinese-language file")
[void]$out.AppendLine("exists in this repository (ATTRIBUTION.md: no source repository was found to read one from).")
[void]$out.AppendLine("English is the closest available original for every row.")
[void]$out.AppendLine()
$rev = (git -C $Root rev-parse --short HEAD 2>$null)
[void]$out.AppendLine("Generated $(Get-Date -Format 'yyyy-MM-dd'), revision: $rev.")
[void]$out.AppendLine()

foreach ($ff in $frenchFiles) {
    $rel = $ff.FullName.Substring($frenchRoot.Length + 1) -replace '\\', '/'
    $frEntries = Get-Entries $ff.FullName
    if ($frEntries.Count -eq 0) { continue }

    $enPath = Join-Path $englishRoot $rel
    $enEntries = Get-Entries $enPath

    [void]$out.AppendLine("## $rel")
    [void]$out.AppendLine()
    [void]$out.AppendLine("| Key or path | Original | English | French |")
    [void]$out.AppendLine("|---|---|---|---|")
    foreach ($key in $frEntries.Keys) {
        $fr = $frEntries[$key]
        $en = $null
        if ($enEntries.Contains($key)) { $en = $enEntries[$key] }
        else { $en = Resolve-DefField $defsRoot $key }
        if ($null -eq $en) { $en = '*(unverified: inherited from a vanilla parent def, not read)*' }
        $orig = $en
        $flag = if ($fr -match '\?\?\?|TODO|\{PAWN_gender' -and $fr -notmatch '\{PAWN_gender \? ') { ' | ?' } else { '' }
        $origCell = ($orig -replace '\|', '\|') -replace "`n", ' '
        $enCell = ($en -replace '\|', '\|') -replace "`n", ' '
        $frCell = ($fr -replace '\|', '\|') -replace "`n", ' '
        $keyCell = $key -replace '\|', '\|'
        [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell$flag |")
    }
    [void]$out.AppendLine()
}

[System.IO.File]::WriteAllText($OutFile, $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "wrote $OutFile"
